# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymitem',
            name='hidden',
            field=models.BooleanField(
                default=False,
                help_text=b'Hide this gym?'),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='last_visit_date',
            field=models.DateField(
                blank=True,
                help_text=b'Date of last visit'),
        ),
    ]
