# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170822_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymitem',
            name='profile',
            field=models.ForeignKey(
                default=1,
                help_text=b'Profile gym item is associated with',
                on_delete=django.db.models.deletion.CASCADE,
                to='app.Profile'
            ),
            preserve_default=False,
        ),
    ]
