# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gymitem_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image_url',
            field=models.CharField(blank=True, help_text=b'URL of image used for Gym', max_length=256, null=True),
        ),
    ]
