# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gym_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_hunter_id',
            field=models.CharField(
                blank=True,
                help_text=b'ID on Gymhuntr',
                max_length=32,
                null=True
            ),
        ),
    ]
