# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170903_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pokemon_go_username',
            field=models.CharField(blank=True, help_text=b'Your name in Pokemon Go', max_length=128, null=True),
        ),
    ]
