# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170903_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='raid_end_date',
            field=models.DateTimeField(blank=True, help_text=b'End Date of Raid', null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='raid_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text=b'Level of Raid', null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='raid_pokemon',
            field=models.CharField(blank=True, help_text=b'Name of Raid Pokemon', max_length=128, null=True),
        ),
    ]
