# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170906_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='raid_end_date',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='raid_level',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='raid_pokemon',
        ),
        migrations.AlterField(
            model_name='gym',
            name='gym_hunter_id',
            field=models.CharField(
                blank=True,
                help_text='ID on Gymhuntr',
                max_length=32,
                null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='image_url',
            field=models.CharField(
                blank=True,
                help_text='URL of image used for Gym',
                max_length=256,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=models.CharField(
                help_text='Location in long,lat format',
                max_length=128
            ),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(
                help_text='Name of Gym',
                max_length=256
            ),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='gym',
            field=models.ForeignKey(
                help_text='Gym item is for',
                on_delete=django.db.models.deletion.CASCADE,
                to='app.Gym'
            ),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='hidden',
            field=models.BooleanField(
                default=False,
                help_text='Hide this gym?'
            ),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='last_visit_date',
            field=models.DateField(
                blank=True,
                help_text='Date of last visit',
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='profile',
            field=models.ForeignKey(
                help_text='Profile gym item is associated with',
                on_delete=django.db.models.deletion.CASCADE,
                to='app.Profile'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemon_go_username',
            field=models.CharField(
                blank=True,
                help_text='Your name in Pokemon Go',
                max_length=128,
                null=True
            ),
        )
    ]
