# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170915_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.CharField(blank=True, help_text='Name of Raid Pokemon', max_length=128, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='Level of Raid', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='End Date of Raid', null=True)),
                ('gym', models.ForeignKey(help_text='Gym raid is on', on_delete=django.db.models.deletion.CASCADE, to='app.Gym')),
            ],
        ),
    ]
