# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 20:09
from __future__ import unicode_literals
from datetime import datetime, time
from django.db import migrations, models


def move_last_visit_date_to_gym_visit_date(apps, schema_editor):
    """
    Copy existing last_visit_date field to new gym_visit_date field
    :param apps: django.db.apps instance
    :param schema_editor: django.db.migrations.schema_editor
    """
    gym_item_model = apps.get_model('app', 'GymItem')
    for gym_item in gym_item_model.objects.all():
        default_time = time(12, 0, 0)
        if gym_item.last_visit_date:
            gym_item.gym_visit_date = datetime.combine(
                gym_item.last_visit_date,
                default_time
            )
            gym_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_raiditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymitem',
            name='gym_visit_date',
            field=models.DateTimeField(
                blank=True,
                help_text='Date visited gym',
                null=True
            ),
        ),
        migrations.RunPython(move_last_visit_date_to_gym_visit_date)
    ]
