# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_gymitem_gym_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymList',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'gyms',
                    models.ManyToManyField(to='app.Gym')
                ),
                (
                    'profile',
                    models.ForeignKey(
                        help_text='Profile gym list is associated with',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.Profile'
                    )
                ),
            ],
        ),
    ]
