# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171218_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tracked_gyms',
            field=models.ManyToManyField(blank=True, to='app.Gym'),
        ),
    ]
