# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_gymlist'),
        ('app', '0015_auto_20171218_0008'),
    ]

    operations = [
    ]
