# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20171218_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='osm_way',
            field=models.CharField(
                blank=True,
                help_text='OSM Way Type',
                max_length=256,
                null=True
            ),
        )
    ]
