# Generated by Django 2.0.1 on 2018-01-14 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_exraidpokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='level_12_s2_cell',
            field=models.CharField(
                blank=True,
                help_text='S2 Cell at level 12',
                max_length=256,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='gym',
            field=models.ForeignKey(
                help_text='Gym item is for',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='app.Gym'
            ),
        ),
        migrations.AlterField(
            model_name='gymitem',
            name='profile',
            field=models.ForeignKey(
                help_text='Profile gym item is associated with',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='app.Profile'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='raiditem',
            name='gym',
            field=models.ForeignKey(
                help_text='Gym raid is on',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='app.Gym'
            ),
        ),
    ]
